 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/aberturas", type: :request do
  
  # Abertura. As you add validations to Abertura, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Abertura.create! valid_attributes
      get aberturas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      abertura = Abertura.create! valid_attributes
      get abertura_url(abertura)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_abertura_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      abertura = Abertura.create! valid_attributes
      get edit_abertura_url(abertura)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Abertura" do
        expect {
          post aberturas_url, params: { abertura: valid_attributes }
        }.to change(Abertura, :count).by(1)
      end

      it "redirects to the created abertura" do
        post aberturas_url, params: { abertura: valid_attributes }
        expect(response).to redirect_to(abertura_url(Abertura.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Abertura" do
        expect {
          post aberturas_url, params: { abertura: invalid_attributes }
        }.to change(Abertura, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post aberturas_url, params: { abertura: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested abertura" do
        abertura = Abertura.create! valid_attributes
        patch abertura_url(abertura), params: { abertura: new_attributes }
        abertura.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the abertura" do
        abertura = Abertura.create! valid_attributes
        patch abertura_url(abertura), params: { abertura: new_attributes }
        abertura.reload
        expect(response).to redirect_to(abertura_url(abertura))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        abertura = Abertura.create! valid_attributes
        patch abertura_url(abertura), params: { abertura: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested abertura" do
      abertura = Abertura.create! valid_attributes
      expect {
        delete abertura_url(abertura)
      }.to change(Abertura, :count).by(-1)
    end

    it "redirects to the aberturas list" do
      abertura = Abertura.create! valid_attributes
      delete abertura_url(abertura)
      expect(response).to redirect_to(aberturas_url)
    end
  end
end
