 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/debites", type: :request do
  
  # Debite. As you add validations to Debite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Debite.create! valid_attributes
      get debites_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      debite = Debite.create! valid_attributes
      get debite_url(debite)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_debite_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      debite = Debite.create! valid_attributes
      get edit_debite_url(debite)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Debite" do
        expect {
          post debites_url, params: { debite: valid_attributes }
        }.to change(Debite, :count).by(1)
      end

      it "redirects to the created debite" do
        post debites_url, params: { debite: valid_attributes }
        expect(response).to redirect_to(debite_url(Debite.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Debite" do
        expect {
          post debites_url, params: { debite: invalid_attributes }
        }.to change(Debite, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post debites_url, params: { debite: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested debite" do
        debite = Debite.create! valid_attributes
        patch debite_url(debite), params: { debite: new_attributes }
        debite.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the debite" do
        debite = Debite.create! valid_attributes
        patch debite_url(debite), params: { debite: new_attributes }
        debite.reload
        expect(response).to redirect_to(debite_url(debite))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        debite = Debite.create! valid_attributes
        patch debite_url(debite), params: { debite: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested debite" do
      debite = Debite.create! valid_attributes
      expect {
        delete debite_url(debite)
      }.to change(Debite, :count).by(-1)
    end

    it "redirects to the debites list" do
      debite = Debite.create! valid_attributes
      delete debite_url(debite)
      expect(response).to redirect_to(debites_url)
    end
  end
end
