 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/fechamentos", type: :request do
  
  # Fechamento. As you add validations to Fechamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Fechamento.create! valid_attributes
      get fechamentos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      fechamento = Fechamento.create! valid_attributes
      get fechamento_url(fechamento)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_fechamento_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      fechamento = Fechamento.create! valid_attributes
      get edit_fechamento_url(fechamento)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Fechamento" do
        expect {
          post fechamentos_url, params: { fechamento: valid_attributes }
        }.to change(Fechamento, :count).by(1)
      end

      it "redirects to the created fechamento" do
        post fechamentos_url, params: { fechamento: valid_attributes }
        expect(response).to redirect_to(fechamento_url(Fechamento.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Fechamento" do
        expect {
          post fechamentos_url, params: { fechamento: invalid_attributes }
        }.to change(Fechamento, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post fechamentos_url, params: { fechamento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fechamento" do
        fechamento = Fechamento.create! valid_attributes
        patch fechamento_url(fechamento), params: { fechamento: new_attributes }
        fechamento.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the fechamento" do
        fechamento = Fechamento.create! valid_attributes
        patch fechamento_url(fechamento), params: { fechamento: new_attributes }
        fechamento.reload
        expect(response).to redirect_to(fechamento_url(fechamento))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        fechamento = Fechamento.create! valid_attributes
        patch fechamento_url(fechamento), params: { fechamento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested fechamento" do
      fechamento = Fechamento.create! valid_attributes
      expect {
        delete fechamento_url(fechamento)
      }.to change(Fechamento, :count).by(-1)
    end

    it "redirects to the fechamentos list" do
      fechamento = Fechamento.create! valid_attributes
      delete fechamento_url(fechamento)
      expect(response).to redirect_to(fechamentos_url)
    end
  end
end
