 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sangria", type: :request do
  
  # Sangrium. As you add validations to Sangrium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Sangrium.create! valid_attributes
      get sangria_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sangrium = Sangrium.create! valid_attributes
      get sangrium_url(sangrium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sangrium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      sangrium = Sangrium.create! valid_attributes
      get edit_sangrium_url(sangrium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Sangrium" do
        expect {
          post sangria_url, params: { sangrium: valid_attributes }
        }.to change(Sangrium, :count).by(1)
      end

      it "redirects to the created sangrium" do
        post sangria_url, params: { sangrium: valid_attributes }
        expect(response).to redirect_to(sangrium_url(Sangrium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Sangrium" do
        expect {
          post sangria_url, params: { sangrium: invalid_attributes }
        }.to change(Sangrium, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sangria_url, params: { sangrium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sangrium" do
        sangrium = Sangrium.create! valid_attributes
        patch sangrium_url(sangrium), params: { sangrium: new_attributes }
        sangrium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sangrium" do
        sangrium = Sangrium.create! valid_attributes
        patch sangrium_url(sangrium), params: { sangrium: new_attributes }
        sangrium.reload
        expect(response).to redirect_to(sangrium_url(sangrium))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sangrium = Sangrium.create! valid_attributes
        patch sangrium_url(sangrium), params: { sangrium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sangrium" do
      sangrium = Sangrium.create! valid_attributes
      expect {
        delete sangrium_url(sangrium)
      }.to change(Sangrium, :count).by(-1)
    end

    it "redirects to the sangria list" do
      sangrium = Sangrium.create! valid_attributes
      delete sangrium_url(sangrium)
      expect(response).to redirect_to(sangria_url)
    end
  end
end
