 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/vendas", type: :request do
  
  # Venda. As you add validations to Venda, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Venda.create! valid_attributes
      get vendas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      venda = Venda.create! valid_attributes
      get venda_url(venda)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_venda_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      venda = Venda.create! valid_attributes
      get edit_venda_url(venda)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Venda" do
        expect {
          post vendas_url, params: { venda: valid_attributes }
        }.to change(Venda, :count).by(1)
      end

      it "redirects to the created venda" do
        post vendas_url, params: { venda: valid_attributes }
        expect(response).to redirect_to(venda_url(Venda.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Venda" do
        expect {
          post vendas_url, params: { venda: invalid_attributes }
        }.to change(Venda, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post vendas_url, params: { venda: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested venda" do
        venda = Venda.create! valid_attributes
        patch venda_url(venda), params: { venda: new_attributes }
        venda.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the venda" do
        venda = Venda.create! valid_attributes
        patch venda_url(venda), params: { venda: new_attributes }
        venda.reload
        expect(response).to redirect_to(venda_url(venda))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        venda = Venda.create! valid_attributes
        patch venda_url(venda), params: { venda: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested venda" do
      venda = Venda.create! valid_attributes
      expect {
        delete venda_url(venda)
      }.to change(Venda, :count).by(-1)
    end

    it "redirects to the vendas list" do
      venda = Venda.create! valid_attributes
      delete venda_url(venda)
      expect(response).to redirect_to(vendas_url)
    end
  end
end
